import OgamePageData from "./OgamePageData.js";
import OGIData from "./OGIData.js";
import { getLogger } from "./logger.js";

const translation = Object.freeze({
  tech: {
    1: {
      de: "Metallmine",
      en: "Metal Mine",
      es: "Mina de metal",
      fr: "Mine de métal",
      tr: "Metal Madeni",
      br: "Mina de Metal",
    },
    2: {
      de: "Kristallmine",
      en: "Crystal Mine",
      es: "Mina de cristal",
      fr: "Mine de cristal",
      tr: "Kristal Madeni",
      br: "Mina de Cristal",
    },
    3: {
      de: "Deuterium-Synthetisierer",
      en: "Deuterium Synthesizer",
      es: "Sintetizador de deuterio",
      fr: "Synthétiseur de deutérium",
      tr: "Deuterium Madeni",
      br: "Sintetizador de Deutério",
    },
    4: {
      de: "Solarkraftwerk",
      en: "Solar Plant",
      es: "Planta de energía solar",
      fr: "Centrale électrique solaire",
      tr: "Solar Enerji Santrali",
      br: "Planta de Energia Solar",
    },
    12: {
      de: "Fusionskraftwerk",
      en: "Fusion Reactor",
      es: "Planta de fusión",
      fr: "Centrale électrique de fusion",
      tr: "Füzyoenerji Santrali",
      br: "Reator de fusão",
    },
    14: {
      de: "Roboterfabrik",
      en: "Robotics Factory",
      es: "Fábrica de robots",
      fr: "Usine de robots",
      tr: "Robot Fabrikası",
      br: "Fabrica de Robos",
    },
    15: {
      de: "Nanitenfabrik",
      en: "Nanite Factory",
      es: "Fábrica de nanobots",
      fr: "Usine de nanites",
      tr: "Nanit Fabrikasi",
      br: "Fabrica de nanites",
    },
    21: {
      de: "Raumschiffswerft",
      en: "Shipyard",
      es: "Hangar",
      fr: "Chantier spatial",
      tr: "Uzay Tersanesi",
      br: "Hangar",
    },
    22: {
      de: "Metallspeicher",
      en: "Metal Storage",
      es: "Almacén de metal",
      fr: "Hangar de métal",
      tr: "Metal Deposu",
      br: "Depósito de metal",
    },
    23: {
      de: "Kristallspeicher",
      en: "Crystal Storage",
      es: "Almacén de cristal",
      fr: "Hangar de cristal",
      tr: "Kristal Deposu",
      br: "Depósito de Cristal",
    },
    24: {
      de: "Deuteriumtank",
      en: "Deuterium Tank",
      es: "Contenedor de deuterio",
      fr: "Réservoir de deutérium",
      tr: "Deuterium Tankeri",
      br: "Deposito de deutério",
    },
    31: {
      de: "Forschungslabor",
      en: "Research Lab",
      es: "Laboratorio de investigación",
      fr: "Laboratoire de recherche",
      tr: "Araştırma Laboratuvarı",
      br: "Laboratório de Pesquisas",
    },
    33: {
      de: "Terraformer",
      en: "Terraformer",
      es: "Terraformer",
      fr: "Terraformeur",
      tr: "Terraformer",
      br: "Terraformador",
    },
    34: {
      de: "Allianzdepot",
      en: "Alliance Depot",
      es: "Depósito de la alianza",
      fr: "Dépôt de ravitaillement",
      tr: "İttifak Deposu",
      br: "Depósito da aliança",
    },
    36: {
      de: "Raumdock",
      en: "Space Dock",
      es: "Astillero orbital",
      fr: "Dock spatial",
      tr: "Uzay İskelesi",
      br: "Estaleiro Espacial",
    },
    41: {
      de: "Mondbasis",
      en: "Lunar Base",
      es: "Base lunar",
      fr: "Base lunaire",
      tr: "Ay Üssü",
      br: "Base Lunar",
    },
    42: {
      de: "Sensorphalanx",
      en: "Sensor Phalanx",
      es: "Sensor Phalanx",
      fr: "Phalange de capteur",
      tr: "Sensör Filanx",
      br: "Sensor Phalanx",
    },
    43: {
      de: "Sprungtor",
      en: "Jump Gate",
      es: "Salto cuántico",
      fr: "Porte de saut spatial",
      tr: "Sıçrama Geçidi",
      br: "Portal de Salto Quântico",
    },
    44: {
      de: "Raketensilo",
      en: "Missile Silo",
      es: "Silo",
      fr: "Silo de missiles",
      tr: "Füze Silosu",
      br: "Silo de mísseis",
    },
    106: {
      de: "Spionagetechnik",
      en: "Espionage Technology",
      es: "Tecnología de espionaje",
      fr: "Technologie Espionnage",
      tr: "Casusluk Tekniği",
      br: "Tecnologia de Espionagem",
    },
    108: {
      de: "Computertechnik",
      en: "Computer Technology",
      es: "Tecnología de computación",
      fr: "Technologie Ordinateur",
      tr: "Bilgisayar Tekniği",
      br: "Tecnologia de Computadores",
    },
    109: {
      de: "Waffentechnik",
      en: "Weapon Technology",
      es: "Tecnología militar",
      fr: "Technologie Armes",
      tr: "Silah Tekniği",
      br: "Tecnologia de armas",
    },
    110: {
      de: "Schildtechnik",
      en: "Shielding Technology",
      es: "Tecnología de defensa",
      fr: "Technologie Bouclier",
      tr: "Kalkan Tekniği",
      br: "Tecnologia de escudo",
    },
    111: {
      de: "Raumschiffpanzerung",
      en: "Armour Technology",
      es: "Tecnología de blindaje",
      fr: "Technologie Protection des vaisseaux spatiaux",
      tr: "Uzay gemisi zırhı",
      br: "Tecnologia de blindagem",
    },
    113: {
      de: "Energietechnik",
      en: "Energy Technology",
      es: "Tecnología de energía",
      fr: "Technologie énergétique",
      tr: "Enerji Tekniği",
      br: "Tecnologia de energia",
    },
    114: {
      de: "Hyperraumtechnik",
      en: "Hyperspace Technology",
      es: "Tecnología de hiperespacio",
      fr: "Technologie hyperespace",
      tr: "Hiperuzay Tekniği",
      br: "Tecnologia de Hiperespaço",
    },
    115: {
      de: "Verbrennungstriebwerk",
      en: "Combustion Drive",
      es: "Motor de combustión",
      fr: "Réacteur à combustion",
      tr: "Yanma motoru",
      br: "Motor de combustão",
    },
    117: {
      de: "Impulstriebwerk",
      en: "Impulse Drive",
      es: "Motor de impulso",
      fr: "Réacteur à impulsion",
      tr: "İtki motoru",
      br: "Motor de impulsão",
    },
    118: {
      de: "Hyperraumantrieb",
      en: "Hyperspace Drive",
      es: "Propulsor hiperespacial",
      fr: "Propulsion hyperespace",
      tr: "Hiperuzay iticisi",
      br: "Motor propulsor de hiperespaço",
    },
    120: {
      de: "Lasertechnik",
      en: "Laser Technology",
      es: "Tecnología láser",
      fr: "Technologie Laser",
      tr: "Lazer Teknolojisi",
      br: "Tecnologia de Laser",
    },
    121: {
      de: "Ionentechnik",
      en: "Ion Technology",
      es: "Tecnología iónica",
      fr: "Technologie à ions",
      tr: "İyon Teknolojisi",
      br: "Tecnologia de íons",
    },
    122: {
      de: "Plasmatechnik",
      en: "Plasma Technology",
      es: "Tecnología de plasma",
      fr: "Technologie Plasma",
      tr: "Plazma Teknolojisi",
      br: "Tecnologia de Plasma",
    },
    123: {
      de: "Intergalaktisches Forschungsnetzwerk",
      en: "Intergalactic Research Network",
      es: "Red de investigación intergaláctica",
      fr: "Réseau de recherche intergalactique",
      tr: "Galaksiler arası araştırma ağı",
      br: "Rede intergalática de pesquisas",
    },
    124: {
      de: "Astrophysik",
      en: "Astrophysics",
      es: "Astrofísica",
      fr: "Astrophysique",
      tr: "Astrofizik",
      br: "Astrofísica",
    },
    199: {
      de: "Gravitonforschung",
      en: "Graviton Technology",
      es: "Tecnología de gravitón",
      fr: "Technologie Graviton",
      tr: "Graviton Teknolojisi",
      br: "Tecnologia de gravitação",
    },
    202: {
      de: "Kleiner Transporter",
      en: "Small Cargo Ship",
      es: "Nave pequeña de carga",
      fr: "Petit transporteur",
      tr: "Küçük Nakliye Gemisi",
      br: "Cargueiro pequeno",
    },
    203: {
      de: "Großer Transporter",
      en: "Large Cargo Ship",
      es: "Nave grande de carga",
      fr: "Grand transporteur",
      tr: "Büyük Nakliye Gemisi",
      br: "Cargueiro Grande",
    },
    204: {
      de: "Leichter Jäger",
      en: "Light Fighter",
      es: "Cazador ligero",
      fr: "Chasseur léger",
      tr: "Hafif Avcı",
      br: "Caça ligeiro",
    },
    205: {
      de: "Schwerer Jäger",
      en: "Heavy Fighter",
      es: "Cazador pesado",
      fr: "Chasseur lourd",
      tr: "Ağır Avcı",
      br: "Caça pesado",
    },
    206: {
      de: "Kreuzer",
      en: "Cruiser",
      es: "Crucero",
      fr: "Croiseur",
      tr: "Kruvazör",
      br: "Cruzador",
    },
    207: {
      de: "Schlachtschiff",
      en: "Battleship",
      es: "Nave de batalla",
      fr: "Vaisseau de bataille",
      tr: "Komuta Gemisi",
      br: "Nave de batalha",
    },
    208: {
      de: "Kolonieschiff",
      en: "Colony Ship",
      es: "Colonizador",
      fr: "Vaisseau de colonisation",
      tr: "Koloni Gemisi",
      br: "Nave Colonizadora",
    },
    209: {
      de: "Recycler",
      en: "Recycler",
      es: "Reciclador",
      fr: "Recycleur",
      tr: "Geri Dönüşümcü",
      br: "Reciclador",
    },
    210: {
      de: "Spionagesonde",
      en: "Espionage Probe",
      es: "Sonda de espionaje",
      fr: "Sonde d`espionnage",
      tr: "Casusluk Sondası",
      br: "Sonda de espionagem",
    },
    211: {
      de: "Bomber",
      en: "Bomber",
      es: "Bombardero",
      fr: "Bombardier",
      tr: "Bombardıman Gemisi",
      br: "Bombardeiro",
    },
    212: {
      de: "Solarsatellit",
      en: "Solar Satellite",
      es: "Satélite solar",
      fr: "Satellite solaire",
      tr: "Solar Uydu",
      br: "Satélite solar",
    },
    213: {
      de: "Zerstörer",
      en: "Destroyer",
      es: "Destructor",
      fr: "Destructeur",
      tr: "Muhrip",
      br: "Destruídor",
    },
    214: {
      de: "Todesstern",
      en: "Death Star",
      es: "Estrella de la muerte",
      fr: "Étoile de la mort",
      tr: "Ölüm Yıldızı",
      br: "Estrela da morte",
    },
    215: {
      de: "Schlachtkreuzer",
      en: "Battlecruiser",
      es: "Acorazado",
      fr: "Traqueur",
      tr: "Fırkateyn",
      br: "Interceptador",
    },
    217: {
      de: "Crawler",
      en: "Crawler",
      es: "Taladrador",
      fr: "Foreuse",
      tr: "Paletli",
      br: "Rastejador",
    },
    218: {
      de: "Reaper",
      en: "Reaper",
      es: "Segador",
      fr: "Faucheur",
      tr: "Azrail",
      br: "Ceifeira",
    },
    219: {
      de: "Pathfinder",
      en: "Pathfinder",
      es: "Explorador",
      fr: "Éclaireur",
      tr: "Rehber",
      br: "Explorador",
    },
    401: {
      de: "Raketenwerfer",
      en: "Rocket Launcher",
      es: "Lazamisiles",
      fr: "Lanceur de missiles",
      tr: "Roketatar",
      br: "Lançador de Mísseis",
    },
    402: {
      de: "Leichtes Lasergeschütz",
      en: "Light Laser",
      es: "Láser pequeño",
      fr: "Artillerie laser légère",
      tr: "Hafif Lazer Topu",
      br: "Laser Pequeno",
    },
    403: {
      de: "Schweres Lasergeschütz",
      en: "Heavy Laser",
      es: "Láser grande",
      fr: "Artillerie laser lourde",
      tr: "Ağır Lazer Topu",
      br: "Laser pesado",
    },
    404: {
      de: "Gaußkanone",
      en: "Gauss Cannon",
      es: "Cañón gauss",
      fr: "Canon de Gauss",
      tr: "Gaus Topu",
      br: "Canhão de Gaus",
    },
    405: {
      de: "Ionengeschütz",
      en: "Ion Cannon",
      es: "Cañón iónico",
      fr: "Artillerie à ions",
      tr: "İyon Topu",
      br: "Canhão de íons",
    },
    406: {
      de: "Plasmawerfer",
      en: "Plasma Turret",
      es: "Cañón de plasma",
      fr: "Lanceur de plasma",
      tr: "Plazma Atıcı",
      br: "Canhão de Plasma",
    },
    407: {
      de: "Kleine Schildkuppel",
      en: "Small Shield Dome",
      es: "Cúpula pequeña de protección",
      fr: "Petit bouclier",
      tr: "Küçük Kalkan Kubbesi",
      br: "Pequeno escudo planetário",
    },
    408: {
      de: "Große Schildkuppel",
      en: "Large Shield Dome",
      es: "Cúpula grande de protección",
      fr: "Grand bouclier",
      tr: "Büyük Kalkan Kubbesi",
      br: "Grande escudo planetário",
    },
    502: {
      de: "Abfangrakete",
      en: "Anti-ballistic Missile",
      es: "Misiles antibalísticos",
      fr: "Missile d`interception",
      tr: "Yakalıyıcı Roketler",
      br: "Míssel de interceptação",
    },
    503: {
      de: "Interplanetarrakete",
      en: "Interplanetary Missile",
      es: "Misil interplanetario",
      fr: "Missile interplanétaire",
      tr: "Gezegenler Arası Roketler",
      br: "Míssel interplanetário",
    },
    label: { de: undefined, en: undefined, es: undefined, fr: undefined, tr: undefined, br: undefined },
  },
  res: {
    0: {
      de: "Metall",
      en: "Metal",
      es: "Metal",
      fr: "Métal",
      tr: "Metal",
      br: "Metal",
    },
    1: {
      de: "Kristall",
      en: "Crystal",
      es: "Cristal",
      fr: "Cristal",
      tr: "Kristal",
      br: "Cristal",
    },
    2: {
      de: "Deuterium",
      en: "Deuterium",
      es: "Deuterio",
      fr: "Deutérium",
      tr: "Deuterium",
      br: "Deutério",
    },
    3: {
      de: "Dunkle Materie",
      en: "Dark Matter",
      es: "Materia oscura",
      fr: "Antimatière",
      tr: "Karanlık Madde",
      br: "Matéria negra",
    },
    4: {
      de: "Energie",
      en: "Energy",
      es: "Energía",
      fr: "Énergie",
      tr: "Enerji",
      br: "Energia",
    },
  },
  text: {
    0: {
      de: "Einstellungen",
      en: "Settings",
      es: "Ajustes",
      fr: "Paramètres",
      tr: "Ayarlar",
      br: "Configurações",
    },
    1: {
      de: "Zielliste",
      en: "Targets list",
      es: "Lista de objetivos",
      fr: "Liste des cibles",
      tr: "Hedefler Listesi",
      br: "Lista de Alvos",
    },
    2: {
      de: "Spielersuche",
      en: "Player search",
      es: "Búsqueda de jugadores",
      fr: "Recherche de joueur",
      tr: "Oyuncu Arama",
      br: "Busca de jogadores",
    },
    3: {
      de: "Statistik",
      en: "Statistics",
      es: "Estadísticas",
      fr: "Statistiques",
      tr: "İstatistikler",
      br: "Estatísticas",
    },
    4: {
      de: "Übersicht",
      en: "Overview",
      es: "Visión general",
      fr: "Aperçu",
      tr: "Genel Bakış",
      br: "Visão geral",
    },
    5: {
      de: "Planetenübersicht",
      en: "Planets overview",
      es: "Visión general de planetas",
      fr: "Aperçu des planètes",
      tr: "Gezegenler Genel Bakışı",
      br: "Visão de planetas",
    },
    6: {
      de: "Hier",
      en: "Here",
      es: "Aquí",
      fr: "Ici",
      tr: "Burada",
      br: "Aqui",
    },
    7: {
      de: "Fehlerberichte",
      en: "Bug reporting",
      es: "Reporte de errores",
      fr: "Rapport de bug",
      tr: "Hata Bildirme",
      br: "Reporte de bugs",
    },
    8: {
      de: "Featureanfrage",
      en: "Feature request",
      es: "Petición de funciones",
      fr: "Demande de fonctionnalité",
      tr: "Özellik İsteği",
      br: "Pedir uma nova função",
    },
    9: {
      de: "Universumseigenschaften",
      en: "Universe characteristics",
      es: "Características del universo",
      fr: "Caractéristiques de l'univers",
      tr: "Evren Özellikleri",
      br: "Características do Universo",
    },
    10: {
      de: "Punkte #1",
      en: "Points #1",
      es: "Puntos #1",
      fr: "Point #1",
      tr: "1.Oyuncunun Puanı",
      br: "Pontos Top #1",
    },
    11: {
      de: "Öko Geschwindigkeit",
      en: "Eco Speed",
      es: "Velocidad economía",
      fr: "Vitesse éco",
      tr: "Ekonomi Hızı",
      br: "Velocidade da economia",
    },
    12: {
      de: "Flottengeschwindigkeit (feindlich)",
      en: "Fleet speed (war)",
      es: "Velocidad de flota (guerra)",
      fr: "Vitesse de flotte (guerre)",
      tr: "Saldırı Filo Hızı",
      br: "Velocidade de naves (Ataque)",
    },
    13: {
      de: "Flottengeschwindigkeit (friedlich)",
      en: "Fleet speed (peaceful)",
      es: "Velocidad de flota (pacífica)",
      fr: "Vitesse de flotte (paisible)",
      tr: "Barışçıl Filo Hızı",
      br: "Velocidade de naves (Pacífica)",
    },
    14: {
      de: "Flottengeschwindigkeit (halten)",
      en: "Fleet speed (hoding)",
      es: "Velocidad de flota (mantener)",
      fr: "Vitesse de la flotte (en attente)",
      tr: "Durma Filo Hızı",
      br: "Velocidade de Naves (Guardar)",
    },
    15: {
      de: "Datenverwaltung",
      en: "Data management",
      es: "Gestión de datos",
      fr: "Gestion de données",
      tr: "Veri Yönetimi",
      br: "Gestão de dados",
    },
    16: {
      de: "Expeditionsdaten",
      en: "Expeditions data",
      es: "Datos de expediciones",
      fr: "Données d'expéditions",
      tr: "Sefer Verileri",
      br: "Dados das expedições",
    },
    17: {
      de: "Kampfdaten",
      en: "Combats data",
      es: "Datos de combates",
      fr: "Données des Combats",
      tr: "Savaş Verileri",
      br: "Dados de combate",
    },
    18: {
      de: "Zieldaten",
      en: "Targets data",
      es: "Datos de objetivos",
      fr: "Données des cibles",
      tr: "Hedef Verileri",
      br: "Dados de alvos",
    },
    19: {
      de: "Gescannte Daten (Galaxie)",
      en: "Scanned data (galaxy)",
      es: "Datos escaneados (galaxia)",
      fr: "Données numérisées (galaxie)",
      tr: "Taranan Veriler (galaksi)",
      br: "Dados escaneados (galaxia)",
    },
    20: {
      de: "Optionsdaten",
      en: "Options data",
      es: "Datos de opciones",
      fr: "Données d'options",
      tr: "Seçenekler Verisi",
      br: "Dados das opções",
    },
    21: {
      de: "Cache und temporäre Daten",
      en: "Cache and Temp data",
      es: "Caché y datos temporales",
      fr: "Données de cache et temporaires",
      tr: "Önbellek ve Geçici Veriler",
      br: "Cache e dados temporários",
    },
    22: {
      de: "Andere Add-On-Daten",
      en: "Other add-on's data",
      es: "Otros datos de la extensión",
      fr: "Données d'autres add-ons",
      tr: "Diğer Eklenti Verileri",
      br: "Outros dados de add-on's",
    },
    23: {
      de: "Aktualisieren",
      en: "Update",
      es: "Actualizar",
      fr: "Mettre à jour",
      tr: "Güncelle",
      br: "Atualizar",
    },
    24: {
      de: "Exportieren",
      en: "Export",
      es: "Exportar",
      fr: "Exportation",
      tr: "Dışa Aktar",
      br: "Exportar",
    },
    25: {
      de: "Importieren",
      en: "Import",
      es: "Importar",
      fr: "Importer",
      tr: "İçe Aktar",
      br: "Importar",
    },
    26: {
      de: "Zurücksetzen",
      en: "Reset",
      es: "Resetear",
      fr: "Réinitialiser",
      tr: "Sıfırla",
      br: "Resetar",
    },
    27: {
      de: "Speichern",
      en: "Save",
      es: "Guardar",
      fr: "Sauvegarder",
      tr: "Kaydet",
      br: "Salvar",
    },
    28: {
      de: "Am Planeten verbleibende Ressourcen",
      en: "Resources to keep on planets",
      es: "Recursos a permanecer en el planeta",
      fr: "Ressources restantes sur la planète",
      tr: "Gezegenlerde saklanacak kaynaklar",
      br: "Recursos para manter nos planetas",
    },
    29: {
      de: "Am Planeten verbleibende Schiffe",
      en: "Ships to keep on planets",
      es: "Naves a permanecer en el planeta",
      fr: "Navires restant sur la planète",
      tr: "Gezegenlerde saklanacak gemiler",
      br: "Naves para manter nos planetas",
    },
    30: {
      de: "Standardmission (eigene)",
      en: "Default mission (own)",
      es: "Misión por defecto (propio)",
      fr: "Mission par défaut (propre)",
      tr: "Varsayılan görev (kendi)",
      br: "Missões padrão (próprias)",
    },
    31: {
      de: "Standardmission (andere)",
      en: "Default mission (others)",
      es: "Misión por defecto (otros)",
      fr: "Mission par défaut (autres)",
      tr: "Varsayılan görev (başkaları)",
      br: "Missões padrão (outras)",
    },
    32: {
      de: "Standardmission (Expedition)",
      en: "Default mission (expedition)",
      es: "Misión por defecto (expedición)",
      fr: "Mission par défaut (expédition)",
      tr: "Varsayılan görev (sefer)",
      br: "Missão padrão (expedições)",
    },
    33: {
      de: "Aktivitätstimer anzeigen",
      en: "Show activity timers",
      es: "Mostrar cronómetros de actividad",
      fr: "Afficher les minuteurs d'activité",
      tr: "Etkinlik zamanlayıcılarını göster",
      br: "Mostrar times de atividade",
    },
    34: {
      de: "Weniger aggressive automatische Aktualisierung des Imperiums",
      en: "Less aggressive empire automatic update",
      es: "Actualización automática del Imperio menos agresiva",
      fr: "Récupération automatique de l'Empire moins agressif",
      tr: "Daha az agresif imparatorluk otomatik güncellemesi",
      br: "Atualização automática do império menos agressiva",
    },
    35: {
      de: "Rentabilitätswert",
      en: "Rentability value",
      es: "Valor de rentabilidad",
      fr: "Valeur de rentabilité",
      tr: "Amortisman değeri",
      br: "Valor de rentabilidade",
    },
    36: {
      de: "Uhren auf die lokale Zeitzone umstellen",
      en: "Change clocks to local time zone",
      es: "Cambiar los relojes a la zona horaria local",
      fr: "Changer les horloges au fuseau horaire local",
      tr: "Saatleri yerel saat dilimine değiştir",
      br: "Mostrar horário local",
    },
    37: {
      de: "Prozentsatz der derzeit im Flug befindlichen Flotte",
      en: "Percentage of fleet currently in flight",
      es: "Porcentaje de flota actualmente en vuelo",
      fr: "Pourcentage de la flotte actuellement en vol",
      tr: "Şu anda uçuşta olan filonun yüzdesi",
      br: "Porcentagem de naves atualmente em vôo",
    },
    38: {
      de: "Fliegend",
      en: "Flying",
      es: "En vuelo",
      fr: "En vol",
      tr: "Havada",
      br: "Viajando",
    },
    39: {
      de: "Fehlend",
      en: "Missing",
      es: "Restante",
      fr: "Manquant",
      tr: "Eksik",
      br: "Restante",
    },
    40: {
      de: "Gesamt",
      en: "Total",
      es: "Total",
      fr: "Total",
      tr: "Toplam",
      br: "Total",
    },
    41: {
      de: "Expeditionen",
      en: "Expeditions",
      es: "Expediciones",
      fr: "Expéditions",
      tr: "Sefer",
      br: "Expedições",
    },
    42: {
      de: "Planet(en)",
      en: "planet(s)",
      es: "planeta(s)",
      fr: "planète(s)",
      tr: "Gezegen",
      br: "Planeta(s)",
    },
    43: {
      de: "Ankunft",
      en: "Arrival",
      es: "Llegada",
      fr: "Arrivée",
      tr: "Varış",
      br: "Chegada",
    },
    44: {
      de: "Dauer",
      en: "Duration",
      es: "Duración",
      fr: "Durée",
      tr: "Süre",
      br: "Duração",
    },
    45: {
      de: "Rückkehr",
      en: "Return",
      es: "Retorno",
      fr: "Retour",
      tr: "Dönüş",
      br: "Retornar",
    },
    46: {
      de: "Keine Missionen...",
      en: "No missions...",
      es: "Ninguna misión...",
      fr: "Aucune mission...",
      tr: "Görev yok...",
      br: "Sem missões...",
    },
    47: {
      de: "Ladekapazität",
      en: "Cargo Capacity",
      es: "Capacidad de carga",
      fr: "Fret",
      tr: "Nakliye Kapasitesi",
      br: "Capacidade de carga",
    },
    48: {
      de: "Geschwindigkeit",
      en: "Speed",
      es: "Velocidad",
      fr: "Vitesse",
      tr: "Hız",
      br: "Velocidade",
    },
    49: {
      de: "Treibstoffverbrauch",
      en: "Fuel Consumption",
      es: "Consumo de combustible",
      fr: "Consommation",
      tr: "Yakıt tüketimi",
      br: "Consumo de combustível",
    },
    50: {
      de: "Amortisationsdauer",
      en: "Payback period",
      es: "Período de amortización",
      fr: "Période de remboursement",
      tr: "Amortisman süresi",
      br: "Tempo de retorno",
    },
    51: {
      de: "Ökonomie",
      en: "Economy",
      es: "Economía",
      fr: "Économie",
      tr: "Ekonomi",
      br: "Economia",
    },
    52: {
      de: "Forschung",
      en: "Research",
      es: "Investigación",
      fr: "Recherche",
      tr: "Araştırma",
      br: "Pesquisa",
    },
    53: {
      de: "Militär",
      en: "Military",
      es: "Militar",
      fr: "Militaire",
      tr: "Askeri",
      br: "Militar",
    },
    54: {
      de: "Verteidigung",
      en: "Defense",
      es: "Defensa",
      fr: "Défense",
      tr: "Savunma",
      br: "Defesa",
    },
    55: {
      de: "Sieg",
      en: "Win",
      es: "Victoria",
      fr: "Gagné",
      tr: "Kazandın",
      br: "Vitória",
    },
    56: {
      de: "Niederlage",
      en: "Lose",
      es: "Derrota",
      fr: "Perdus",
      tr: "Kaybettin",
      br: "Derrota",
    },
    57: {
      de: "Unentschieden",
      en: "Draw",
      es: "Empate",
      fr: "Match nul",
      tr: "Berabere",
      br: "Empate",
    },
    58: {
      de: "API in die Zwischenablage kopiert",
      en: "API Key copied in clipboard",
      es: "Clave API copiada al portapapeles",
      fr: "Clé API copiée dans le presse-papiers",
      tr: "API Anahtarı panoya kopyalandı",
      br: "Api Key copiada para área de transferência",
    },
    59: {
      de: "Verhältnis",
      en: "Ratio",
      es: "Ratio",
      fr: "Rapport",
      tr: "Oran",
      br: "Média",
    },
    60: {
      de: "Stunde",
      en: "Hour",
      es: "Hora",
      fr: "Heure",
      tr: "Saatlik Üretim",
      br: "Hora",
    },
    61: {
      de: "Tag",
      en: "Day",
      es: "Día",
      fr: "Jour",
      tr: "Günlük Üretim",
      br: "Dia",
    },
    62: {
      de: "Woche",
      en: "Week",
      es: "Semana",
      fr: "Semaine",
      tr: "Haftalık Üretim",
      br: "Semana",
    },
    63: {
      de: "Flotte",
      en: "Fleet",
      es: "Flota",
      fr: "Flotte",
      tr: "Filo",
      br: "Frota",
    },
    64: {
      de: "Schiffe",
      en: "ships",
      es: "naves",
      fr: "navires",
      tr: "Gemi",
      br: "Naves",
    },
    65: {
      de: "Recycling",
      en: "Recycling",
      es: "Reciclaje",
      fr: "Recyclage",
      tr: "GD Kapasitesi",
      br: "Reciclagem",
    },
    66: {
      de: "Für diese Funktionen ist der Commander erforderlich ...",
      en: "The commander officier is required for these features...",
      es: "El oficial comandante es necesario para estas funciones...",
      fr: "L'officier de commandement est requis pour ces fonctions...",
      tr: "Bu özellikler için komutan subayı gereklidir...",
      br: "O comandante é necessário para essa função",
    },
    67: {
      de: "Ressourcen",
      en: "Resources",
      es: "Recursos",
      fr: "Ressources",
      tr: "Kaynaklar",
      br: "Recursos",
    },
    68: {
      de: "Verluste",
      en: "Losses",
      es: "Pérdidas",
      fr: "Pertes",
      tr: "Kayıplar",
      br: "Perdas",
    },
    69: {
      de: "Recycled",
      en: "Recycled",
      es: "Reciclado",
      fr: "Recyclé",
      tr: "Hurda",
      br: "Reciclado",
    },
    70: {
      de: "Treibstoff",
      en: "Fuel",
      es: "Combustible",
      fr: "Carburant",
      tr: "Harcanan Deu",
      br: "Combustível",
    },
    71: {
      de: "S. Loch",
      en: "B. Hole",
      es: "Agujero negro",
      fr: "Trou noir",
      tr: "Kara Delik",
      br: "Buraco Negro",
    },
    72: {
      de: "Beste Kämpfe",
      en: "Best combats",
      es: "Mejores combates",
      fr: "Meilleurs combats",
      tr: "En iyi Savaşlar",
      br: "Melhores combates",
    },
    73: {
      de: "Name",
      en: "Name",
      es: "Nombre",
      fr: "Nom",
      tr: "Adı",
      br: "Nome",
    },
    74: {
      de: "Beute",
      en: "Loot",
      es: "Botín",
      fr: "Pillage",
      tr: "Ganimet",
      br: "Faturamento",
    },
    75: {
      de: "Schaden",
      en: "Damage",
      es: "Daños",
      fr: "Dommage",
      tr: "Hasar",
      br: "Danos",
    },
    76: {
      de: "Trümmerfeld",
      en: "Debris",
      es: "Escombros",
      fr: "Débris",
      tr: "Enkaz alanı",
      br: "Destroços",
    },
    77: {
      de: "Anpassen",
      en: "Adjust",
      es: "Ajuste",
      fr: "Ajuster",
      tr: "Ayarla",
      br: "Ajuste",
    },
    78: {
      de: "Items",
      en: "Items",
      es: "Ítems",
      fr: "Items",
      tr: "Öğeler",
      br: "Itens",
    },
    79: {
      de: "Aliens",
      en: "Aliens",
      es: "Alienígenas",
      fr: "Aliens",
      tr: "Yabancılar",
      br: "Alienígenas",
    },
    80: {
      de: "Piraten",
      en: "Pirates",
      es: "Piratas",
      fr: "Pirates",
      tr: "Korsanlar",
      br: "Piratas",
    },
    81: {
      de: "Verspätung",
      en: "Late",
      es: "Retraso",
      fr: "En retard",
      tr: "Geç",
      br: "Atraso",
    },
    82: {
      de: "Frühzeitig",
      en: "Early",
      es: "Adelanto",
      fr: "En avance",
      tr: "Erken",
      br: "Adiantado",
    },
    83: {
      de: "Leer",
      en: "Empty",
      es: "Vacío",
      fr: "Vide",
      tr: "Boş",
      br: "Vazio",
    },
    84: {
      de: "Händler",
      en: "Merchant",
      es: "Mercader",
      fr: "Marchands",
      tr: "Tüccar",
      br: "Mercador",
    },
    85: {
      de: "Produktion",
      en: "Production",
      es: "Producción",
      fr: "Production",
      tr: "Üretim",
      br: "Produção",
    },
    86: {
      de: "Kampf",
      en: "Combat",
      es: "Combate",
      fr: "Combat",
      tr: "Savaş Araştırmaları",
      br: "Combate",
    },
    87: {
      de: "Antrieb",
      en: "Drive",
      es: "Propulsión",
      fr: "Propulsion",
      tr: "Sürüş Araştırmaları",
      br: "Propulsão",
    },
    88: {
      de: "Empfohlene Weiterentwicklung",
      en: "Recommended further development",
      es: "Desarrollo posterior recomendado",
      fr: "Développement ultérieur recommandé",
      tr: "Tavsiye edilen ileri geliştirme (Amortisman Hesabı)",
      br: "Desenvolvimento recomendado para o futuro",
    },
    89: {
      de: "Lebensformen",
      en: "Lifeforms",
      es: "Formas de vida",
      fr: "Forme de vie",
      tr: "Canlı Türleri",
      br: "Formas de vida",
    },
    90: {
      de: "Minen",
      en: "Mines",
      es: "Minas",
      fr: "Mines",
      tr: "Madenler",
      br: "Minas",
    },
    91: {
      de: "Allgemein",
      en: "General",
      es: "General",
      fr: "Général",
      tr: "Genel",
      br: "General",
    },
    92: {
      de: "Kämpfe",
      en: "Combats",
      es: "Combates",
      fr: "Combat",
      tr: "Savaşlar",
      br: "Combates",
    },
    93: {
      de: "Astro",
      en: "Astro",
      es: "Astro",
      fr: "Astro",
      tr: "Astro",
      br: "Astro",
    },
    94: {
      de: "Computer",
      en: "Computer",
      es: "Computación",
      fr: "Ordinateur",
      tr: "Bilgisayar T.",
      br: "Computadores",
    },
    95: {
      de: "Hyperraum",
      en: "Hyperspace",
      es: "Hiperespacio",
      fr: "Hyperespace",
      tr: "Hiperuzay T.",
      br: "Hiperespaço",
    },
    96: {
      de: "Plasma",
      en: "Plasma",
      es: "Plasma",
      fr: "Plasma",
      tr: "Plazma",
      br: "Plasma",
    },
    97: {
      de: "Datum",
      en: "Date",
      es: "Fecha",
      fr: "Date",
      tr: "Tarih",
      br: "Data",
    },
    98: {
      de: "Koordinaten",
      en: "Coords",
      es: "Coordenadas",
      fr: "Coordonnées",
      tr: "Koordinatlar",
      br: "Coordenadas",
    },
    99: {
      de: "Beute",
      en: "Loot",
      es: "Botín",
      fr: "Butin",
      tr: "Ganimet",
      br: "Faturamento",
    },
    100: {
      de: "Flotte",
      en: "Fleet",
      es: "Flota",
      fr: "Flotte",
      tr: "Filo",
      br: "Frota",
    },
    101: {
      de: "Standard Expeditionsdauer",
      en: "Default expedition time",
      es: "Tiempo de expedición predeterminado",
      fr: "Heure d'expédition par défaut",
      tr: "Varsayılan sefer süresi",
      br: "Tempo padrão da epedição",
    },
    102: {
      de: "Aktionen",
      en: "Actions",
      es: "Acciones",
      fr: "Actions",
      tr: "Eylemler",
      br: "Ações",
    },
    103: {
      de: "Optionen",
      en: "Options",
      es: "Opciones",
      fr: "Options",
      tr: "Seçenekler",
      br: "Opções",
    },
    104: {
      de: "Automatisches Löschen von nicht rentablen Berichten aktivieren/deaktivieren, unter Berücksichtigung von: Plünderung, Flotten- und Verteidigungstrümmerfeld (Deuterium zu Trümmerfeld und 70% Verteidigungsreparatur werden angenommen).",
      en: "Enable/Disable automatic deletion of unprofitable reports taking into account: looting, fleet and defense debris field (deuterium to debris field and 70% defense repair are assumed).",
      es: "Habilitar/Deshabilitar la eliminación automática de informes no rentables teniendo en cuenta: saqueo, campo de escombros de flota y defensa (se asume deuterio al campo de escombros y 70% de reparación de defensa).",
      fr: "Activer/Désactiver la suppression automatique des rapports non rentables en tenant compte  du pillage, du champ de ruine de la flotte et de la défense (on suppose que le deuterium se transforme en champ de ruine et que 70 % de la défense est réparée).",
      tr: "Karlı olmayan raporların otomatik silinmesini etkinleştir/devre dışı bırakma: yağma, filo ve savunma enkaz alanı (deuteriumdan enkaz alanına ve %70 savunma onarımı varsayılmaktadır).",
      br: "Ativar/Desativar atuomaticamente a detecção de reports não rentavéis: faturamento, destroços de frota e defesa (Deutério gasto até os destroços e custos de reparo de 70% da defesa são considerados)",
    },
    105: {
      de: "Minimale Rentabilität, um als interessant angesehen zu werden",
      en: "Minimal target rentability to be considered as interesting",
      es: "Retabilidad mínima de un objetivo para ser considerado interesante",
      fr: "Rentabilité minimale d'une cible pour être considéré comme intéressante",
      tr: "İlginç kabul edilecek en düşük hedef karlılık",
      br: "Rentabilidade mínima desejada",
    },
    106: {
      de: "Spionagetabelle aktivieren/deaktivieren",
      en: "Toggle spy table",
      es: "Activar/desactivar la tabla de espionajes",
      fr: "Active/désactive le tableau d'espionnage",
      tr: "Casusluk tablosunu etkinleştir/devre dışı bırak",
      br: "Ativar/Desativar tabela de espionagens",
    },
    107: {
      de: "Nicht genügend Transportschiffe...",
      en: "Not enough cargo ships...",
      es: "No hay suficientes naves de transporte...",
      fr: "Pas assez de navires de transport...",
      tr: "Yeterli kargo gemisi yok...",
      br: "Total de cargueiros insuficientes...",
    },
    108: {
      de: "Kein Kampfschiff...",
      en: "No combat ship...",
      es: "Ninguna nave de combate...",
      fr: "Pas de vaisseau militaire...",
      tr: "Savaş gemisi yok...",
      br: "Sem naves de combate...",
    },
    109: {
      de: "Keine Spionagesonde...",
      en: "No Espionage Probe...",
      es: "Ninguna sonda de espionaje...",
      fr: "Pas de sonde d'espionnage...",
      tr: "Casusluk Sondası yok...",
      br: "Nenhuma sonda de espionagem...",
    },
    110: {
      de: "Kein Pathfinder...",
      en: "No Pathfinder...",
      es: "Ningún explorador...",
      fr: "Pas d'éclaireur...",
      tr: "Rehber yok...",
      br: "Sem explorador...",
    },
    111: {
      de: "Keine Mission...",
      en: "No mission...",
      es: "Ninguna misión...",
      fr: "Pas de mission...",
      tr: "Görev yok...",
      br: "Nenhuma missão...",
    },
    112: {
      de: "Unbekannte Expeditionsnachricht...",
      en: "Unknown expedition message...",
      es: "Mensaje de expedición desconocido...",
      fr: "Message d'expédition inconnu...",
      tr: "Bilinmeyen sefer mesajı...",
      br: "Mensagem de expedição desconhecida...",
    },
    113: {
      de: "Hilf mir alle zu finden",
      en: "Help me find them all",
      es: "Ayúdame a encontrarlos todos",
      fr: "Aidez-moi à les trouver tous",
      tr: "Onları bulmama yardım et !",
      br: "Me ajude a encontrar todos",
    },
    114: {
      de: "Warnung: Expeditionsposition wird schwach...",
      en: "Warning: expedition position is getting weak...",
      es: "Atención: la posición de expediciones está saturándose...",
      fr: "Attention: la position d'expédition devient saturée...",
      tr: "Uyarı: Sefer konumu zayıflıyor...",
      br: "Atenção: posição da expedição está ficando ruim...",
    },
    115: {
      de: "Fehler: Keine Schiffe ausgewählt",
      en: "Error: No ships selected",
      es: "Error: ninguna nave seleccionada",
      fr: "Erreur: aucun navire sélectionné",
      tr: "Hata: Hiç gemi seçilmedi",
      br: "Erro: Sem naves selecionadas",
    },
    116: {
      de: "Fehler: Keine Mission verfügbar",
      en: "Error: No mission available",
      es: "Error: ninguna misión disponible",
      fr: "Erreur: aucune mission disponible",
      tr: "Hata: Kullanılabilir görev yok",
      br: "Erro: Sem missões disponíveis",
    },
    117: {
      de: "Fehler: Aktueller Planet/Mond",
      en: "Error: Current planet/moon",
      es: "Error: planeta/luna actual",
      fr: "Erreur: planète/lune actuelle",
      tr: "Hata: Mevcut gezegen/ay",
      br: "Erro: Planeta/Lua atual",
    },
    118: {
      de: "Keine neue Kolonie",
      en: "No new colony",
      es: "Ninguna colonia nueva",
      fr: "Pas de nouvelle colonie",
      tr: "Yeni koloni yok",
      br: "Nenhuma colônia nova",
    },
    119: {
      de: "Handelskurs",
      en: "Trade rate",
      es: "Ratio de cambio",
      fr: "Taux d'échange",
      tr: "Ticaret oranı",
      br: "Taxa de troca",
    },
    120: {
      de: "Rentabilität",
      en: "Profitability",
      es: "Rentabilidad",
      fr: "Rentabilité",
      tr: "Amortisman",
      br: "Rentabilidade",
    },
    121: {
      de: "Die Amortisationszeit errechnet sich aus der Differenz der Gesamtproduktion und den Kosten für die Zielstufe. Ausreichende Energieversorgung und unveränderte globale Produktionsbooster (Spieler- und Allianzklasse, Offiziere) werden vorausgesetzt. Zur Bewertung der Ressourcen wird der angegebene Handelskurs verwendet. Bei Minen wird die Änderung der Gesamtproduktion durch erhöhtes Crawler-Limit berücksichtigt, dabei wird der Produktionsfaktor und eine eventuelle Begrenzung wie angegeben verwendet. Für die Astrophysik werden die Forschungskosten und die Kosten für den Bau von Minen auf der neuen Kolonie bis zum Durchschnittslevel berücksichtigt. Die Produktionsänderung wird durch die durchschnittliche Planetenparameter angenähert, da die tatsächliche Produktion von der Temperatur und der Position der neuen Kolonie abhängt. Baukosten für die Energieversorgung oder andere Anlagen werden nicht berücksichtigt.",
      en: "The payback period is calculated based on the difference in total production and the cost for the target level. Sufficient energy supply and unchanged global production boosters (player and alliance class, officers) are assumed. The configured trade rate is used to value the resources. For mines the change of total production dueto increased crawler limit is taken into account, using the settings from above. For Astrophysics the research cost and the cost of building mines to the average level on the new colony are taken into account. The change in production its approximated by the average planet parameters, because the actual production depends on the new colony's temperature and position. Building costs for energy supply or other facilities are not considered.",
      es: "El período de amortización está calculado basándose en la diferencia en la producción total y el coste para el nivel objetivo. Se asume un suficiente aprovisionamiento energético y que los mejoradores de producción (clases de jugador y alianza, oficiales) permanecen inalterados. El ratio de cambio configurado se usa para valorar los recursos. Para las minas, se tiene en cuenta el cambio de la producción total debido al incremento de taladradores, usando los ajustes superiores. Para la astrofísica, se tiene en cuenta el coste de investigación y el coste de construcción de minas al nivel promedio en la nueva colonia. El cambio en la producción es aproximado usando parámetros promedio para el planeta, porque la producción real depende de la temperatura y posición de la nueva colonia. No se tienen en cuenta costes de construcción de aprovisionamiento de energía ni de otras instalaciones.",
      fr: "La période de remboursement est calculée en fonction de la différence entre la production totale et le coût pour le niveau cible. Un approvisionnement énergétique suffisant et des boosters de production globaux inchangés (classe de joueur et d'alliance, officiers) sont supposés. Le taux d'échange configuré est utilisé pour évaluer les ressources. Pour les mines, le changement de production totale dû à l'augmentation de la limite de foreuses est pris en compte, en utilisant les paramètres ci-dessus. Pour l'astrophysique, le coût de recherche et le coût de construction des mines au niveau moyen sur la nouvelle colonie sont pris en compte. Le changement de production est approximé par les paramètres moyens de la planète, car la production réelle dépend de la température et de la position de la nouvelle colonie. Les coûts de construction pour l'approvisionnement en énergie ou d'autres installations ne sont pas pris en compte.",
      tr: "Geri ödeme süresi, toplam üretimdeki farka ve hedef seviyenin maliyetine göre hesaplanır. Yeterli enerji arzı ve değişmeyen küresel üretim artırıcıları (oyuncu ve ittifak sınıfı, görevliler) varsayılır. Yapılandırılan ticaret oranı, değeri belirlemek için kullanılır. kaynaklar. Madenler için, artan paletli sınırına bağlı olarak toplam üretimdeki değişiklik, yukarıdan yapılan ayarlar kullanılarak dikkate alınır. Astrofizik için araştırma maliyeti ve yeni kolonide mayın inşa etme maliyeti ortalama seviyeye dikkate alınır. Üretimdeki değişiklik, ortalama gezegen parametrelerine yakındır, çünkü gerçek üretim yeni koloninin sıcaklığına ve konumuna bağlıdır. Enerji tedariki veya diğer tesisler için inşaat maliyetleri dikkate alınmaz.",
      br: "O período de retorno é calculado baseado na diferença no total de produção e o custo para o level alvo. Assume-se que haja energia suficiente e reforços de produção globais (classes de jogador, aliança e oficiais) são considerados. A taxa de negociação configurada é considerada para avaliar os recursos. Para minas, a alteração da produção total devido ao aumento do limite re rastreadores é considerado, usando as configurações acima. Para astrofísica, são levados em consideração o custo da pesquisa e o custo médio de construção das minas ao nivel médio de uma nova colônia. A mudança na produção é aproximada pelos parâmetros médios pois a produção real depende da temperatura e posição da nova colônia. Os custos para construção de fornecimento de energia e outras instalações não são considerados.",
    },
    122: {
      de: "Nur Werte größer oder gleich 1 ...",
      en: "Only values greater or equal to 1 allowed...",
      es: "Sólo valores superiores o iguales a 1 están permitidos...",
      fr: "Seules les valeurs supérieures ou égales à 1 sont autorisées...",
      tr: "Sadece 1'e eşit veya daha büyük değerler izin verilir...",
      br: "Apenas valores maiores que 1 são permitidos...",
    },
    123: {
      de: "Alle Nachrichten löschen",
      en: "Delete all messages",
      es: "Borrar todos los mensajes",
      fr: "Supprimer tous les messages",
      tr: "Tüm mesajları sil",
      br: "Apagar todas as mensagens",
    },
    124: {
      de: "Feindliche Spionageberichte löschen",
      en: "Delete enemy spy reports",
      es: "Borrar los informes de espionaje enemigos",
      fr: "Supprimer les rapports d'espionnage ennemis",
      tr: "Düşman casus raporlarını sil",
      br: "Apagar relatórios de espionagem de inimigos",
    },
    125: {
      de: "Wenn aktiviert, wird die Anzahl der Crawler mit den derzeit gebauten Crawlern begrenzt.",
      en: "If activated, the number of crawlers will be limited with the currently built crawlers.",
      es: "Si está activado, el número de taladradores se limitará al número actual de construidos.",
      fr: "S'il est activé, le nombre de foreuses sera limité à celles actuellement construites.",
      tr: "Etkinleştirildiğinde, paletlilerin sayısı şu anda üretilen paletlilerle sınırlanır.",
      br: "Se ativado, o numero de rastejadores será limitado ao numero atual de rastejadores construídos.",
    },
    126: {
      de: "Crawler Produktionsfaktor",
      en: "Crawler production factor",
      es: "Factor de producción de los taladradores",
      fr: "Facteur de production des foreuses",
      tr: "Paletli üretim faktörü",
      br: "Fator de produção dos rastejadores",
    },
    127: {
      de: "Ziel",
      en: "Destination",
      es: "Destino",
      fr: "Destination",
      tr: "Hedef",
      br: "Destino",
    },
    128: {
      de: "Ressourcentransport",
      en: "Resource transport",
      es: "Transporte de recursos",
      fr: "Transport des ressources",
      tr: "Nakliye",
      br: "Transporte de recursos",
    },
    129: {
      de: "Abriss",
      en: "Demolition",
      es: "Demolición",
      fr: "Démolition",
      tr: "Yıkım",
      br: "Demolição",
    },
    130: {
      de: "Filter",
      en: "Filter",
      es: "Filtro",
      fr: "Filtre",
      tr: "Filtre",
      br: "Filtro",
    },
    131: {
      de: "Kapazität",
      en: "Capacity",
      es: "Capacidad",
      fr: "Capacité",
      tr: "Kapasite",
      br: "Capacidade",
    },
    132: {
      de: "Füllzeit",
      en: "Filling time",
      es: "Tiempo de llenado",
      fr: "Temps de remplissage",
      tr: "Dolum süresi",
      br: "Tempo de preenchimento",
    },
    133: {
      de: "Beitragen oder Bugs melden",
      en: "Contribute or bug report",
      es: "Contribuir o reportar errores",
      fr: "Contribuer ou signaler un bug",
      tr: "Katkıda bulunun veya hata bildirin",
      br: "Contribuir ou relatar um bug",
    },
    134: {
      de: "Flottenaktivität der Planeten anzeigen",
      en: "Display planets fleet activity",
      es: "Mostrar actividad de flota de los planetas",
      fr: "Afficher l'activité de la flotte des planètes",
      tr: "Gezegenlerin filo etkinliğini görüntüle",
      br: "Mostrar atividade de frota dos planetas",
    },
    135: {
      de: "Filter invertieren",
      en: "Invert filter",
      es: "Invertir filtro",
      fr: "Inverser le filtre",
      tr: "Filtreyi ters çevir",
      br: "Inverter filtro",
    },
    136: {
      de: "Forschungsgeschwindigkeit",
      en: "Research speed",
      es: "Velocidad de investigación",
      fr: "Vitesse de recherche",
      tr: "Araştırma hızı",
      br: "Velocidade de pesquisa",
    },
    137: {
      de: "Aktivität",
      en: "Activity",
      es: "Actividad",
      fr: "Activité",
      tr: "Etkinlik",
      br: "Atividade",
    },
    138: {
      de: "Navigationspfeile in mobiler Version anzeigen",
      en: "Navigation arrows in mobile version",
      es: "Flechas de navegación en versión móvil",
      fr: "Flèches de navigation en version mobile",
      tr: "Mobil sürümde gezinme okları",
      br: "Setas de navegação na versão mobile",
    },
    139: {
      de: "Entdeckungen",
      en: "Discoveries",
      es: "Descubrimientos",
      fr: "Découvertes",
      tr: "Keşifler",
      br: "Descobertas",
    },
    140: {
      de: "Menschen",
      en: "Human",
      es: "Humanos",
      fr: "Les humains",
      tr: "İnsanlar",
      br: "Humanos",
    },
    141: {
      de: "Rock’tal",
      en: "Rock’tal",
      es: "Rock`tal",
      fr: "Roctas",
      tr: "Rock’tal",
      br: "Rock’tal",
    },
    142: {
      de: "Mechas",
      en: "Mechas",
      es: "Mecas",
      fr: "Mécas",
      tr: "Mekalar",
      br: "Mechas",
    },
    143: {
      de: "Kaelesh",
      en: "Kaelesh",
      es: "Kaelesh",
      fr: "Kaeleshs",
      tr: "Kaelesh",
      br: "Kaelesh",
    },
    144: {
      de: "Erfahrung",
      en: "Experience",
      es: "Experiencia",
      fr: "Expérience",
      tr: "Deneyim",
      br: "Experiência",
    },
    145: {
      de: "Artefakte",
      en: "Artefacts",
      es: "Artefactos",
      fr: "Artéfacts",
      tr: "Artefaktlar",
      br: "Artefatos",
    },
    146: {
      de: "Abgeschlossenen Vorgang anzeigen",
      en: "Indicate finished process",
      es: "Indicar proceso terminado",
      fr: "Indiquer les processus terminé",
      tr: "Tamamlanmış işlemi belirt",
      br: "Indicar fim de processo",
    },
    147: {
      de: "Externe Tools",
      en: "External Tools",
      es: "Herramientas externas",
      fr: "Outils externes",
      tr: "Diğer Araçlar",
      br: "Ferramentas externas",
    },
    148: {
      de: "Standardmissionen",
      en: "Default missions",
      es: "Misiónes por defecto",
      fr: "Missions par défaut",
      tr: "Tamamlanmış görevler",
      br: "Missões padrão",
    },
    149: {
      de: "Expeditionsfrachtlimit (%)",
      en: "Expedition cargo limit (%)",
      es: "Límite de carga de expedición (%)",
      fr: "Limite de fret d'expédition (%)",
      tr: "Sefer kargo limiti (%)",
      br: "Limite de carga na expedição (%)",
    },
    150: {
      de: "Expeditionen vor der Rotation",
      en: "Expeditions before rotation",
      es: "Expediciones antes de rotación",
      fr: "Expéditions avant rotation",
      tr: "Rotasyon öncesi sefer gezileri",
      br: "Número de expedições antes da rotação",
    },
    151: {
      de: "Fehler: kein PTRE-Teamkey registriert",
      en: "Error: no PTRE teamkey registered",
      es: "Error: ninguna clave de equipo PTRE registrada",
      fr: "Erreur : aucune clé d'équipe PTRE enregistrée",
      tr: "Hata: hiçbir takım anahtarı PTRE kaydedilmedi",
      br: "Erro: Sem chave de equipe do PTRE registrada",
    },
    152: {
      de: "Bester Bericht",
      en: "Best report",
      es: "Mejor informe",
      fr: "Meilleur rapport",
      tr: "En i̇yi rapor",
      br: "Melhor reporte",
    },
    153: {
      de: "Berichtsdetails",
      en: "Report details",
      es: "Detalles del informe",
      fr: "Détails du rapport",
      tr: "Rapor detayları",
      br: "Detalhes do reporte",
    },
    154: {
      de: "Zielprofil",
      en: "Target profile",
      es: "Perfil del objetivo",
      fr: "Profil de la cible",
      tr: "Hedef profili",
      br: "Perfil do alvo",
    },
    155: {
      de: "- Keine Aktivität erkannt",
      en: "- No activity detected",
      es: "- Ninguna actividad detectada",
      fr: "- Aucune activité détectée",
      tr: "- Hiçbir etkinlik algılanmadı",
      br: "- Sem atividade detectada",
    },
    156: {
      de: "- Einige Aktivitäten erkannt",
      en: "- A few activities detected",
      es: "- Unas pocas actividades detectadas",
      fr: "- Peu d'activités détectées",
      tr: "- Birkaç etkinlik algılandı",
      br: "- Pouca atividade detectada",
    },
    157: {
      de: "- Einige Aktivitäten erkannt",
      en: "- Some activities detected",
      es: "- Algunas actividades detectadas",
      fr: "- Quelques activités détectées",
      tr: "- Bazı etkinlikler algılandı",
      br: "- Algumas atividades detectadas",
    },
    158: {
      de: "- Viele Aktivitäten erkannt",
      en: "- A lot of activities detected",
      es: "- Muchas actividades detectadas",
      fr: "- Beaucoup d'activités détectées",
      tr: "- Çok sayıda etkinlik algılandı",
      br: "- Muita atividade detectada",
    },
    159: {
      de: "<br>- Perfekt überprüft",
      en: "<br>- Perfectly checked",
      es: "<br>- Perfectamente verificado",
      fr: "<br>- Parfaitement vérifié",
      tr: "<br>- Mükemmel kontrol edildi",
      br: "<br>- Verificado perfeitamente",
    },
    160: {
      de: "<br>- Gut überprüft",
      en: "<br>- Nicely checked",
      es: "<br>- Bien verificado",
      fr: "<br>- Bien vérifié",
      tr: "<br>- Güzel kontrol edildi",
      br: "<br>- Verificação boa",
    },
    161: {
      de: "<br>- Ordentlich überprüft",
      en: "<br>- Decently checked",
      es: "<br>- Aceptablemente verificado",
      fr: "<br>- Moyennement vérifié",
      tr: "<br>- Uygun bir şekilde kontrol edildi",
      br: "<br>- Verificação decente",
    },
    162: {
      de: "Schlecht überprüft",
      en: "Poorly checked",
      es: "Pobremente verificado",
      fr: "Mal vérifié",
      tr: "Kötü kontrol edildi",
      br: "Verificação ruim",
    },
    163: {
      de: "Nicht überprüft",
      en: "Not checked",
      es: "No verificado",
      fr: "Non vérifié",
      tr: "Kontrol edilmedi",
      br: "Não verificado",
    },
    164: {
      de: "Fehlende Schiffe für die ausgewählte Flottenzusammensetzung...",
      en: "Not enough ships for the chosen fleet composition...",
      es: "No hay suficientes naves para la composición de flota escogida...",
      fr: "Vaisseaux manquants pour la composition de flotte choisie...",
      tr: "Seçilen filo bileşimi için eksik gemiler...",
      br: "Sem naves suficientes para a composição de frota escolhida...",
    },
    165: {
      de: "Verwendung für Expeditionen",
      en: "Use for expeditions",
      es: "Usar para expediciones",
      fr: "Utiliser pour les expéditions",
      tr: "Sefer gezileri için kullanın",
      br: "Usar para expedições",
    },
    166: {
      de: undefined,
      en: undefined,
      es: undefined,
      fr: undefined,
      tr: undefined,
      br: undefined,
    },
    167: {
      de: "Entdeckungsdaten",
      en: "Discoveries data",
      es: "Datos de descubrimientos",
      fr: "Données de découvertes",
      tr: "Keşifler Verileri",
      br: "Dados de descobertas",
    },
    168: {
      de: "Daten werden geladen. Bitte warten...",
      en: "Loading data. Please, wait...",
      es: "Cargando datos. Por favor, espere...",
      fr: "Chargement des données. Veuillez patienter...",
      tr: "Veri yükleniyor. Lütfen bekleyin...",
      br: "Carregando dados. Por favor, aguarde...",
    },
    169: {
      de: "Externes Tool nicht in 'Einstellung' konfiguriert",
      en: "External tool not configured in 'Settings'",
      es: "Herramienta externa sin configurar en 'Ajustes'",
      fr: "Outil externe non configuré dans 'Paramètres'",
      tr: "Harici takım 'Ayarlar' da yapılandırılmamış",
      br: "Ferramenta externa não configurada nos 'Ajustes'",
    },
    170: {
      de: "Kampfsimulator",
      en: "Battle simulator",
      es: "Simulador de batallas",
      fr: "Simulateur de combat",
      tr: "Savaş simülatörü",
      br: "Simulador de batalhas",
    },
    171: {
      de: "Wähle eine Option...",
      en: "Select option...",
      es: "Seleccionar opción...",
      fr: "Sélectionnez l'option...",
      tr: "Seçeneği seçin...",
      br: "Selecione uma opção...",
    },
    172: {
      de: "Letzte zurückrufen",
      en: "Recall latest",
      es: "Retirar último",
      fr: "Rappel dernier",
      tr: "Geri çağrı son",
      br: "Voltar último",
    },
    173: {
      de: "Einh.",
      en: "Units",
      es: "Uds.",
      fr: "Uts",
      tr: "Birim",
      br: "Unid.",
    },
    174: {
      de: "MSE",
      en: "MSU",
      es: "UME",
      fr: "USM",
      tr: "MSB",
      br: "SEM",
    },
    175: {
      de: "KSE",
      en: "CSU",
      es: "UCE",
      fr: "USC",
      tr: "CSB",
      br: "SEC",
    },
    176: {
      de: "DSE",
      en: "DSU",
      es: "UDE",
      fr: "USD",
      tr: "DSB",
      br: "SED",
    },
    177: {
      de: "Summe in Einheiten von Ressourcen",
      en: "Sum in units of resources",
      es: "Suma en unidades de recursos",
      fr: "Somme en unités de ressources",
      tr: "Kaynak birimlerinde toplam",
      br: "Soma em unidades de recursos",
    },
    178: {
      de: "Summe als Metallstandardeinheit",
      en: "Sum as metal standard unit",
      es: "Suma en unidades de metal equivalente",
      fr: "Somme en unité standard de métal",
      tr: "Metal standart birimi olarak toplam",
      br: "Soma equivalente em metal",
    },
    179: {
      de: "Summe als Kristallstandardeinheit",
      en: "Sum as crystal standard unit",
      es: "Suma en unidades de cristal equivalente",
      fr: "Somme en unité standard de cristal",
      tr: "Kristal standart birimi olarak toplam",
      br: "Soma equivalente em cristal",
    },
    180: {
      de: "Summe als Deuteriumstandardeinheit",
      en: "Sum as deuterium standard unit",
      es: "Suma en unidades de deuterio equivalente",
      fr: "Somme en unité standard de deutérium",
      tr: "Döteryum standart birimi olarak toplam",
      br: "Soma equivalente em deutério",
    },
    181: {
      de: "Standard-Ressourceneinheit",
      en: "Resource standard unit",
      es: "Unidad estándar de recursos",
      fr: "Unité standard de ressources",
      tr: "Standart kaynak birimi",
      br: "Unidade padrão de recursos",
    },
    182: {
      de: "Spionageberichte anhängen, wenn Sie die Seite wechseln",
      en: "Append spy reports when you switch page",
      es: "Adjuntar informes de espionaje al cambiar de página",
      fr: "Ajouter les rapports d'espionnage lorsque vous changez de page",
      tr: "Sayfa değiştirdiğinizde casus raporlarını ekle",
      br: "Anexar relatórios de espionagem ao mudar de página",
    },
    183: {
      de: "Feindliche Flotten",
      en: "Hostile fleets",
      es: "Flotas hostiles",
      fr: "Flottes hostiles",
      tr: "Düşman filoları",
      br: "Frotas hostis",
    },
    184: {
      de: "Standardmäßig",
      en: "Default",
      es: "Por defecto",
      fr: "Par défaut",
      tr: "Varsayılan olarak",
      br: "Por padrão",
    },
    185: {
      de: "Gepulstes Symbol",
      en: "Pulsed icon",
      es: "Icono pulsante",
      fr: "Icone animé",
      tr: "Darbeli simge",
      br: "Ícone pulsado",
    },
    186: {
      de: "Gepulster Hintergrund",
      en: "Pulsed background",
      es: "Fondo pulsante",
      fr: "Arrière plan animé",
      tr: "Darbeli arka plan",
      br: "Fundo pulsado",
    },
    187: {
      de: "Alarmmodus für feindliche Flotten",
      en: "Hostile Fleet Alert Mode",
      es: "Modo de alerta de flota hostil",
      fr: "Mode d'alerte de flotte hostile",
      tr: "Düşman Filosu Uyarı Modu",
      br: "Modo de alerta de frota hostil",
    },
    188: {
      de: "Öffnen Sie den Spionagebericht",
      en: "Open the spy report",
      es: "Abrir el informe de espionaje",
      fr: "Ouvrir le rapport d'espionnage",
      tr: "Casus raporunu aç",
      br: "Abrir o relatório de espionagem",
    },
    189: {
      de: "Rentabilitätswert (Feindsicht)",
      en: "Profitability value (enemy point of view)",
      es: "Valor de la rentabilidad (punto de vista del enemigo)",
      fr: "Valeur de rentabilité (point de vue ennemi)",
      tr: "Kârlılık değeri (düşman bakış açısı)",
      br: "Valor de rentabilidade (ponto de vista inimigo)",
    },
    190: {
      de: "Ihre Mindestrentabilität, um von Feinden als interessant angesehen zu werden",
      en: "Your minimum profitability to be considered interesting by the enemy",
      es: "Tu rentabilidad mínima para ser considerado interesante por el enemigo",
      fr: "Votre rentabilité minimale pour être considéré comme intéressante par l'ennemi",
      tr: "Yeterli kârınız düşman tarafından ilginç olarak kabul edilmesi için",
      br: "Seu lucro mínimo para ser considerado interessante pelo inimigo",
    },
    191: {
      de: undefined,
      en: undefined,
      es: undefined,
      fr: undefined,
      tr: undefined,
      br: undefined,
    },
  },
});

const language = OgamePageData.playerLang;
let currentLanguage = ["ar", "mx"].includes(language) ? "es" : language;
currentLanguage = ["de", "en", "es", "fr", "tr", "br"].includes(currentLanguage) ? currentLanguage : "en";

class Translator {
  logger = getLogger("Translator");

  #getTranslations() {
    const translations = OGIData.json.translations ?? {};
    if (!translations.lfTypeNames) translations.lfTypeNames = {};
    if (!translations.tech) translations.tech = {};
    if (!translations.text) translations.text = {};
    if (!translations.language) translations.language = {};
    if (!translations.lastUpdate) translations.lastUpdate = new Date(0);

    return translations;
  }
  #translate(id, type = "text") {
    return translation?.[type]?.[id]?.[currentLanguage] || translation?.[type]?.[id]?.en || "";
  }
  translate(id, type = "text") {
    if (OGIData.json.translations && type === "tech") {
      return OGIData.json.translations.tech[id];
    }
    return this.#translate(id, type);
  }

  GetClassFromLifeformName(name) {
    const translations = this.#getTranslations();
    return translations.lfTypeNames[name];
  }

  #ForceUpdateAllTechNamesFromEmpire(translations, empire) {
    const regex = /^\d+$/;
    Object.keys(empire.translations.planets).forEach((key) => {
      if (!key.endsWith("_full")) {
        if (regex.test(key)) {
          translations.tech[key] = empire.translations.planets[`${key}_full`].trim();
        } else {
          translations.text[key] = empire.translations.planets[key].trim();
        }
      }
    });
  }

  UpdateAllTechNamesFromEmpire(empireFromPlanets, empireFromMoons) {
    const translations = this.#getTranslations();
    const diffInMinutes = Math.floor((new Date() - new Date(translations.lastUpdate)) / (1000 * 60));

    //if langage is different from currentLanguage or if date is older than 60 minutes update
    if (translations.language !== currentLanguage || diffInMinutes > 60) {
      this.logger.debug(`Translations (${currentLanguage}) will be updated`);

      this.#ForceUpdateAllTechNamesFromEmpire(translations, empireFromPlanets);
      this.#ForceUpdateAllTechNamesFromEmpire(translations, empireFromMoons);

      //set date to now and language to currentLanguage
      translations.lastUpdate = new Date().toISOString();
      translations.language = currentLanguage;

      OGIData.json.translations = translations;

      this.logger.debug(`Translations (${currentLanguage}) updated`);
    } else {
      this.logger.debug(
        `No need to update translations (${currentLanguage}), last update was ${diffInMinutes} minutes ago`
      );
    }
  }

  InitializeLFNames(currentPosition, hasLifeforms) {
    if (!hasLifeforms) return;
    const translations = this.#getTranslations();
    fetch(`/game/index.php?page=ingame&component=lfsettings&cp=${currentPosition.id}`)
      .then((rep) => rep.text())
      .then((str) => {
        const htmlDocument = new window.DOMParser().parseFromString(str, "text/html");
        const listName = htmlDocument.querySelectorAll("div.lfsettingsContent > h3");
        listName.forEach((lfName) => {
          const lifeformIcon = lfName.parentElement.querySelector(".lifeform1, .lifeform2, .lifeform3, .lifeform4");
          translations.lfTypeNames[lfName.textContent.trim()] = lifeformIcon.classList[1];
        });
        OGIData.json.translations = translations;
        // last fetch has to be from current planet/moon else Ogame switches on next refresh
        if (currentPosition.isMoon) fetch(currentPosition.planet.querySelector(".moonlink").href);
      });
  }
}

export default new Translator();
